site_name: sports_prediction_framework
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [sports_prediction_framework]

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: usage.md
  - Database Connection: database_connect.md
  - Examples: examples.md
  - Commented Workflow: workflow_comment.md
  - Data Loading: loader.md
  - Data Handling: wrapper.md
  - Iterative Training - Scope: scope.md
  - Base Model: base_model.md
  - Training: training.md
  - Optimizer: optimizer.md
  - Simulation: simulation.md
  - API Reference:
    - dataloader: reference/dataloader.md
    - datawrapper:
      - Base wrappers: reference/datawrapper_base.md
      - Advanced wrappers: reference/datawrapper_advanced.md
    - transformer:
      - transformations: reference/transformations.md
      - scope: reference/scope.md
      - data_selector: reference/data_selector.md
    - learner: reference/learner.md
    - model:
      - Base model: reference/base_model.md
      - Neural model: reference/neural_model.md
      - Torch model: reference/torch_model.md
    - optimizer: reference/optimizer.md
    - simulation:
       - Base class: reference/simulation.md
       - Simulation implementations: reference/simulation_advanced.md

